config/routes.rb
GoogleAnalytics::Application.routes.draw do
  resources :ninjas

  root :to => 'ninjas#index'

end

app/models/ninja.rb
class Ninja < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ninjas_controller.rb
class NinjasController < ApplicationController
  # GET /ninjas
  # GET /ninjas.json
  def index
    @ninjas = Ninja.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ninjas }
    end
  end

  # GET /ninjas/1
  # GET /ninjas/1.json
  def show
    @ninja = Ninja.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ninja }
    end
  end

  # GET /ninjas/new
  # GET /ninjas/new.json
  def new
    @ninja = Ninja.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ninja }
    end
  end

  # GET /ninjas/1/edit
  def edit
    @ninja = Ninja.find(params[:id])
  end

  # POST /ninjas
  # POST /ninjas.json
  def create
    @ninja = Ninja.new(params[:ninja])

    respond_to do |format|
      if @ninja.save
        format.html { redirect_to @ninja, notice: 'Ninja was successfully created.' }
        format.json { render json: @ninja, status: :created, location: @ninja }
      else
        format.html { render action: "new" }
        format.json { render json: @ninja.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ninjas/1
  # PUT /ninjas/1.json
  def update
    @ninja = Ninja.find(params[:id])

    respond_to do |format|
      if @ninja.update_attributes(params[:ninja])
        format.html { redirect_to @ninja, notice: 'Ninja was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ninja.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ninjas/1
  # DELETE /ninjas/1.json
  def destroy
    @ninja = Ninja.find(params[:id])
    @ninja.destroy

    respond_to do |format|
      format.html { redirect_to ninjas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ninjas_helper.rb
module NinjasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoogleAnalytics</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36889691-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</body>
</html>

app/views/ninjas/_form.html.erb
<%= form_for(@ninja) do |f| %>
  <% if @ninja.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ninja.errors.count, "error") %> prohibited this ninja from being saved:</h2>

      <ul>
      <% @ninja.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ninjas/edit.html.erb
<h1>Editing ninja</h1>

<%= render 'form' %>

<%= link_to 'Show', @ninja %> |
<%= link_to 'Back', ninjas_path %>

app/views/ninjas/index.html.erb
<h1>Listing ninjas</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ninjas.each do |ninja| %>
  <tr>
    <td><%= ninja.name %></td>
    <td><%= link_to 'Show', ninja %></td>
    <td><%= link_to 'Edit', edit_ninja_path(ninja) %></td>
    <td><%= link_to 'Destroy', ninja, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ninja', new_ninja_path %>

app/views/ninjas/new.html.erb
<h1>New ninja</h1>

<%= render 'form' %>

<%= link_to 'Back', ninjas_path %>

app/views/ninjas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ninja.name %>
</p>


<%= link_to 'Edit', edit_ninja_path(@ninja) %> |
<%= link_to 'Back', ninjas_path %>